const lang_id= {
    "home":`Beranda`,
    "portfolio":`Portofolio`,
    "exp":`Pengalaman`,
    "greet": `Halo, nama saya <span class="break-mobile"><b>Irwan Sahrul Sidik</b><span>`,
    "intro": `Saya seorang Full-Stack Web Developer dengan pengalaman ekstensif selama lebih dari 4 tahun. Keahlian saya adalah membuat dan merancang Situs Web, Aplikasi, Mockups, dan banyak lagi.`,
    "cv":"CV Saya",
    'xp_intro':`Pengalaman luar biasa dengan perusahaan dan organisasi tersebut.`,
    'xp_mvt':`Sebagai Consultant Programmer, Mengerjakan berbagai proyek untuk klien MVT.
    <br><span class="date">Des 2019 -  Sekarang</span>.`,
    'xp_tsel':`Sebagai Web Developer untuk Pengembangan dan pembuatan aplikasi internal Telkomsel dibawah naungan Telkom Sigma <br><span class="date">Des 2019 -  Sekarang</span>.`,
    'xp_ajv':`Pengerjaan Aplikasi Perlombaan upload Video kolaborasi AJVE.org dengan Transjakarta, Walhi dan Kehati.  <br><span class="date">November 2020 -  Januari 2021</span>.`,
    'xp_usakti':`Pengerjaan Aplikasi voting untuk pemilihan ketua organisasi ikatan alumni usakti. <br><span class="date">Desember 2020 -  Januari 2021</span>.`,
    'portfolio':`Portofolio`,
    'portfolio_all':`Semua`,
    'portfolio_os':`Toko Online`,
    'portfolio_sm':`Media Sosial`,
    'portfolio_app':`Aplikasi`,
    'portfolio_erp':`ERP`,
    'portfolio_more':`Portofolio Lainnya`,
    'footer_text':`lakukan sesuatu yang bermanfaat. selalu dibuat dengan cinta`,
    'launch':`Lihat`,
    'launch_wa':`Info`,
    'content_title':'Memulai Startup',
    'content_1':`Layanan Kumpulan Aplikasi Komputasi Awan, <br>
    kumpulan aplikasi pendukung produktivitas. temukan kebutuhan produktivitas Anda dalam satu layanan aplikasi.`,
    'content_2':`Layanan Pengembangan Situs Web dan Aplikasi. <br>
    Membantu individu atau bisnis membuat aplikasi atau situs mereka sendiri.`,
    'content_3':`Layanan Obrolan Langsung untuk website dan aplikasi kamu. <br> Pendukung Customer, Bot Obrolan & Integrasi API.`,
    'find':`Temukan`,
};


const lang_en={
    "home":`Home`,
    "portfolio":`Portfolio`,
    "exp":`Experience`,
    "greet": `Hello, my name is <span class="break-mobile"><b>Irwan Sahrul Sidik</b></span>`,
    "intro": `I am a Full-Stack Web Developer with over 4 years of extensive experience. My specialty is creating and designing Websites, Apps, Mockups and more.`,
    "cv":"MyCV",
    'xp_intro':`Amazing experience with those companies and organizations.`,
    'xp_mvt':`As a Consultant Programmer, Working on various projects for MVT clients. <br> <span class = "date"> Dec 2019 - Present </span>.`,
    'xp_tsel': `As a Web Developer for developing and creating internal Telkomsel applications under Telkom Sigma <br> <span class = "date"> Dec 2019 - Present </span>.`,
    'xp_ajv':`Work on the Application for AJVE.org collaboration video upload competition with Transjakarta, Walhi and Kehati. <br> <span class = "date"> November 2020 - January 2021 </span>.`,
    'xp_usakti':`Work on voting applications for the election of the chairman of the usakti alumni association. <br> <span class = "date"> December 2020 - January 2021 </span>.`,
    'portfolio':`Portfolio`,
    'portfolio_all':`All`,
    'portfolio_os':`Online Shop`,
    'portfolio_sm':`Sosial Media`,
    'portfolio_app':`Apps`,
    'portfolio_erp':`ERP`,
    'portfolio_more':`More Portfolio`,
    'footer_text':`do something useful. always made with love`,
    'launch':`Launch`,
    'launch_wa':`Info`,
    'content_title':'started a Startup',
    'content_1':`Cloud Application Collection Service,<br> a collection of productivity support applications. find your productivity needs in one application service.`,
    'content_2':`Website and Application Development Services.<br> Helping individuals or businesses create their own app or site.`,
    'content_3':`Live Chat Service for your website and application. <br> Customer Support, Chat Bot & API Integration.`,
    'find':`Find`,

};